# 应用名称
spring:
  application:
    name: blog
#  数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver

# 应用服务 WEB 访问端口
server:
  port: 8081
#    日志信息
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
